### ISSUE TITLE
Upstairs disk stats -> Oximeter

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/crucible#341]
Gather some "basic" disk stats and send them to oximeter

**Comment by bnaecker** [comment]
Thanks @leftwo, let me know how I can help here. The actual creation and generation of the statistics should be fairly straightforward. I'm less sure how to get the data out, since I'm not familiar with how the upstairs can talk to Nexus, via Propolis I'm guessing.

**Comment by smklein** [comment]
Just tested on main - if i `zlogin` to a running Propolis zone, I can ping the Nexus IP address. So routing from the propolis zone -> nexus zone should work.

(I'm gonna pick up the work on https://github.com/oxidecomputer/omicron/issues/718 again, so hopefully it can just refer to Nexus' DNS name, rather than an IP)

**Comment by leftwo** [comment]
The Propolis side work is [here](https://github.com/oxidecomputer/propolis/pull/147).
The library user (Propolis) will now give the upstairs a `ProducerRegistry` it can use to register its own stats.

**Comment by leftwo** [comment]
This first pass is done!
