### ISSUE TITLE
Crucible upstairs should get disk UUID from propolis/volume layer.

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/crucible#345]
Each upstairs needs to have a unique UUID.
This could come from Nexus or the volume layer, but some consideration will need to be given to
the volume layer allowing multiple upstairs parts to make a larger region.  I'm not sure exactly how this
will work..

**Comment by jmpesp** [comment]
The first step is to address the fact that the IDs are currently random :)

Currently when Nexus creates a volume construction request, no ID is specified, and the volume code assigns a random one. https://github.com/oxidecomputer/crucible/pull/358 changes this so that during the creation of the construction request, Nexus must specify an ID.

After that, each Volume object in the topology will have it's own ID.

**Comment by jmpesp** [comment]
With https://github.com/oxidecomputer/omicron/pull/1368, Nexus is now specifying required IDs. Closing this issue.
