### ISSUE TITLE
You can't depend on dependencies

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/crucible#655]
The downstairs currently assumes any job ID issued before the most recent flush has been completed:

https://github.com/oxidecomputer/crucible/blob/75519cb2dc91be78ee5792718575e5348ddbdc1c/downstairs/src/lib.rs#L2585

This breaks the dependency model where a read does not depend on a flush and a flush does not depend
on a previous read.  This can possibly introduce reads landing on different downstairs in a different order, 
resulting in different data being returned.

Consider this example.

Read block 0
Flush
Write block 0

The read has no dependencies, so it can go whenever.
The flush has no dependencies, so it can go whenever.
The write requires the flush.

On downstairs 1, the flush could go first, then the write, then the read.  The read would get data from the write.
On downstairs 2, the read could go first (and get original block 0 data), then the flush, then the write.

Even if the write depends on the read, because the downstairs stops checking dependencies with job IDs
lower than the most recent flush, it can't tell the difference between the read not having yet arrived, and it
having arrived before the flush.

**Comment by jmpesp** [comment]
We discussed this issue out-of-band a bit and I'll summarize: the line `if dep <= &self.last_flush` is **not** an optimization, it's because our code was designed and written with the assumption that flushes are barriers to all jobs. One (read: I) can't simply relax that without reworking that design decision, and that has implications for reconciliation and online repair and probably the whole code base.
